/-
Copyright (c) 2026 Quang Dao. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/

module
public import Mathlib.Basic.Real.ENatENNReal
public import VCVio.CryptoFoundations.FiatShamir.Sigma.Stateful.Bridge
public import VCVio.StateSeparating.IdenticalUntilBad

/-!
# Stateful Fiat-Shamir CMA game hops

The theorems here are stated directly over `QueryImpl.Stateful` handlers and the
concrete `CmaState` product state.
-/

@[expose] public section

universe u

open ENNReal OracleSpec OracleComp ProbComp
open OracleComp.ProgramLogic.Relational

namespace FiatShamir.Stateful

variable (M Commit Chal : Type)
variable {Stmt Wit : Type} {rel : Stmt → Wit → Bool}
variable {Resp PrvState : Type}

/-! ## H3 state invariants and per-query loss -/

/-- Initial direct CMA data, without the trailing bad flag. -/
@[reducible] def cmaDataInit (M Commit Chal Stmt Wit : Type) :
    CmaData M Commit Chal Stmt Wit :=
  ([], ∅, none)

/-- The direct CMA initial state is the initial data with bad unset. -/
@[simp]
lemma cmaInit_eq_cmaDataInit :
    cmaInit M Commit Chal Stmt Wit = (cmaDataInit M Commit Chal Stmt Wit, false) := rfl

/-- Reachability invariant for the direct CMA data.

Cached keypairs, when present, must satisfy the relation generated by `hr.gen`.
The invariant is intentionally phrased on `CmaData`, not heap cells. -/
def CmaData.Valid
    {M : Type} {Commit : Type} {Chal Stmt Wit : Type}
    {rel : Stmt → Wit → Bool}
    (s : CmaData M Commit Chal Stmt Wit) : Prop :=
  match s.2.2 with
  | none => True
  | some (pk, sk) => rel pk sk = true

instance
    {M : Type} {Commit : Type} {Chal Stmt Wit : Type}
    {rel : Stmt → Wit → Bool}
    (s : CmaData M Commit Chal Stmt Wit) :
    Decidable (CmaData.Valid (rel := rel) s) := by
  unfold CmaData.Valid
  rcases s.2.2 with _ | ⟨pk, sk⟩ <;> infer_instance

/-- The initial direct CMA data has no cached keypair, hence satisfies the
valid-keypair invariant. -/
lemma cmaDataInit_valid :
    CmaData.Valid (rel := rel) (cmaDataInit M Commit Chal Stmt Wit) := by
  simp [CmaData.Valid]

/-- Tight state-dependent per-signing-query loss for H3 on reachable states. -/
noncomputable def cmaSignEpsCore
    (ζ_zk β : ℝ≥0∞) (s : CmaData M Commit Chal Stmt Wit) : ℝ≥0∞ :=
  ζ_zk + QueryCache.enncard s.2.1 * β

/-- State-dependent per-signing-query loss for H3.

On reachable states this is `ζ_zk + QueryCache.enncard · β`. Invalid keypair states
receive the conservative fallback cost `1`, which is useful for ungated
identical-until-bad statements. -/
noncomputable def cmaSignEps
    (ζ_zk β : ℝ≥0∞) (s : CmaData M Commit Chal Stmt Wit) : ℝ≥0∞ :=
  if CmaData.Valid (rel := rel) s then
    cmaSignEpsCore M Commit Chal ζ_zk β s
  else
    1

section H3Obligations

variable [DecidableEq M] [DecidableEq Commit] [SampleableType Chal]

/-! ## H3 proof obligations -/

/-- Signing queries are the charged queries in the H3 hop. -/
abbrev cmaH3Costly :
    (cmaSpec M Commit Chal Resp Stmt).Domain → Prop :=
  IsCostlyQuery (M := M) (Commit := Commit) (Chal := Chal)
    (Resp := Resp) (Stmt := Stmt)

/-- Boolean distinguishing advantage for the H3 pair from the direct initial CMA state. -/
noncomputable abbrev cmaH3Advantage
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) Bool) : ℝ≥0∞ :=
  (cmaReal M Commit Chal σ hr).advantage
    (cmaInit M Commit Chal Stmt Wit)
    (cmaSim M Commit Chal hr simT)
    (cmaInit M Commit Chal Stmt Wit)
    A

/-- Expected accumulated H3 signing loss in the real game. -/
noncomputable abbrev cmaH3ExpectedLoss
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (ζ_zk β : ℝ≥0∞)
    {α : Type}
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) α)
    (qS : ℕ) : ℝ≥0∞ :=
  expectedQuerySlack (cmaReal M Commit Chal σ hr)
    (cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
      (Resp := Resp) (Stmt := Stmt))
    (cmaSignEpsCore M Commit Chal ζ_zk β) A qS
    (cmaInit M Commit Chal Stmt Wit)

/-- Per-query facts for the H3 hop. -/
structure CmaH3StepFacts
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (ζ_zk β : ℝ≥0∞) : Prop where
  /-- The real game preserves keypair validity while bad is false. -/
  preservesValid :
    (cmaReal M Commit Chal σ hr).PreservesNoBadInvariant
      (CmaData.Valid (rel := rel))
  /-- Signing queries are close by the state-dependent H3 loss. -/
  stepTvCostly :
    ∀ (t : (cmaSpec M Commit Chal Resp Stmt).Domain),
      cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt) t →
      ∀ (s : CmaData M Commit Chal Stmt Wit),
        CmaData.Valid (rel := rel) s →
          etvDist
            (((cmaReal M Commit Chal σ hr) t).run (s, false))
            (((cmaSim M Commit Chal hr simT) t).run (s, false))
            ≤ cmaSignEpsCore M Commit Chal ζ_zk β s
  /-- Non-signing queries agree pointwise. -/
  stepEqFree :
    ∀ (t : (cmaSpec M Commit Chal Resp Stmt).Domain),
      ¬ cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
          (Resp := Resp) (Stmt := Stmt) t →
      ∀ (p : CmaState M Commit Chal Stmt Wit),
        ((cmaReal M Commit Chal σ hr) t).run p =
          ((cmaSim M Commit Chal hr simT) t).run p
  /-- Once the real bad flag is true, it stays true. -/
  badMono :
    ∀ (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
      (p : CmaState M Commit Chal Stmt Wit), p.2 = true →
        ∀ z ∈ support (((cmaReal M Commit Chal σ hr) t).run p), z.2.2 = true

/-- Computation-specific facts for applying the H3 hop. -/
structure CmaH3RunFacts
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (ζ_zk β : ℝ≥0∞)
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) Bool)
    (qS : ℕ) (εBound : ℝ≥0∞) : Prop where
  /-- The adversary issues at most `qS` signing queries. -/
  queryBound : OracleComp.IsQueryBoundP A
    (cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
      (Resp := Resp) (Stmt := Stmt)) qS
  /-- The real game never reaches bad from the initial state. -/
  badZero :
    Pr{let z ← ((simulateQ (cmaReal M Commit Chal σ hr) A).run
      (cmaInit M Commit Chal Stmt Wit))}[z.2.2 = true] = 0
  /-- The expected accumulated signing loss is at most the requested bound. -/
  expectedLossLe :
    cmaH3ExpectedLoss M Commit Chal σ hr ζ_zk β A qS ≤ εBound

/-! ## Real-game bad flag facts -/

/-- Stepwise preservation of a trailing Boolean flag lifts through
`simulateQ`. -/
theorem simulateQ_bad_preserved_of_step
    {ι ι' : Type} {spec : OracleSpec ι} {spec' : OracleSpec ι'}
    {σ : Type} {α : Type}
    (impl : QueryImpl spec (StateT (σ × Bool) (OracleComp spec')))
    (hstep : ∀ (t : spec.Domain) (p : σ × Bool) (z),
      z ∈ support ((impl t).run p) → z.2.2 = p.2)
    (oa : OracleComp spec α) (p : σ × Bool) {z : α × σ × Bool}
    (hz : z ∈ support ((simulateQ impl oa).run p)) :
    z.2.2 = p.2 := by
  induction oa using OracleComp.inductionOn generalizing p z with
  | pure x => simp_all
  | query_bind t k ih =>
      simp only [simulateQ_bind, simulateQ_query, OracleQuery.cont_query,
        OracleQuery.input_query, id_map, StateT.run_bind, support_bind,
        Set.mem_iUnion, exists_prop] at hz
      obtain ⟨up, hup, hz⟩ := hz
      exact (ih up.1 up.2 hz).trans (hstep t p up hup)

/-- Unified per-step structure of `cmaReal`: at every query, the bad flag is
preserved, the `Valid` predicate is preserved on the data, and the random-oracle
cache count grows by at most one if and only if the query is `cmaH3Costly` or
`IsHashQuery`. The three callable corollaries below are projections of this
single case-blast. -/
private theorem cmaReal_step_normal_form
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
    (p : CmaState M Commit Chal Stmt Wit)
    (z : (cmaSpec M Commit Chal Resp Stmt).Range t × CmaState M Commit Chal Stmt Wit)
    (hz : z ∈ support (((cmaReal M Commit Chal σ hr) t).run p)) :
    z.2.2 = p.2 ∧
    (CmaData.Valid (rel := rel) p.1 → CmaData.Valid (rel := rel) z.2.1) ∧
    QueryCache.enncard z.2.1.2.1 ≤ QueryCache.enncard p.1.2.1 +
      (if cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
            (Resp := Resp) (Stmt := Stmt) t ∨
          IsHashQuery (M := M) (Commit := Commit) (Chal := Chal)
            (Resp := Resp) (Stmt := Stmt) t then (1 : ℝ≥0∞) else 0) := by
  rcases p with ⟨⟨log, cache, keypair⟩, bad⟩
  rcases t with n | mc | m | ⟨⟩
  · simp only [fs_simp, cmaH3Costly, IsCostlyQuery, IsHashQuery, false_or, ite_false,
      StateT.run_mk, support_bind, Set.mem_iUnion, support_pure, Set.mem_singleton_iff,
      exists_prop] at hz ⊢
    obtain ⟨r, _, rfl⟩ := hz
    exact ⟨rfl, fun h => by simpa [CmaData.Valid] using h, by simp⟩
  · simp only [fs_simp, cmaH3Costly, IsCostlyQuery, IsHashQuery, false_or, ite_true,
      StateT.run_mk] at hz ⊢
    cases hcache : cache mc with
    | none =>
        simp only [hcache, support_bind, Set.mem_iUnion, support_pure, Set.mem_singleton_iff,
          exists_prop] at hz
        obtain ⟨r, _, rfl⟩ := hz
        exact ⟨rfl, fun h => by simpa [CmaData.Valid] using h,
          QueryCache.enncard_cacheQuery_le cache mc r⟩
    | some r =>
        simp only [hcache, support_pure, Set.mem_singleton_iff] at hz
        subst z
        exact ⟨rfl, fun h => by simpa [CmaData.Valid] using h, le_self_add⟩
  · simp only [fs_simp, cmaH3Costly, IsCostlyQuery, IsHashQuery, true_or, ite_true,
      StateT.run_mk] at hz ⊢
    rcases keypair with keypair | ⟨pk, sk⟩
    · simp only [support_bind, Set.mem_iUnion, exists_prop] at hz
      obtain ⟨pk_sk, hgen, i, _, hrest⟩ := hz
      cases hcache : cache (m, i.1) with
      | none =>
          simp only [hcache, support_bind, Set.mem_iUnion, exists_prop, support_pure,
            Set.mem_singleton_iff] at hrest
          obtain ⟨ch, _, π, _, rfl⟩ := hrest
          exact ⟨rfl, fun _ => hr.gen_sound pk_sk.1 pk_sk.2 hgen,
            QueryCache.enncard_cacheQuery_le cache (m, i.1) ch⟩
      | some ch =>
          simp only [hcache, support_bind, Set.mem_iUnion, support_pure,
            Set.mem_singleton_iff, exists_prop] at hrest
          obtain ⟨π, _, rfl⟩ := hrest
          exact ⟨rfl, fun _ => hr.gen_sound pk_sk.1 pk_sk.2 hgen, le_self_add⟩
    · simp only [support_bind, Set.mem_iUnion, exists_prop] at hz
      obtain ⟨i, _, hrest⟩ := hz
      cases hcache : cache (m, i.1) with
      | none =>
          simp only [hcache, support_bind, Set.mem_iUnion, support_pure,
            Set.mem_singleton_iff, exists_prop] at hrest
          obtain ⟨ch, _, π, _, rfl⟩ := hrest
          exact ⟨rfl, fun h => by simpa [CmaData.Valid] using h,
            QueryCache.enncard_cacheQuery_le cache (m, i.1) ch⟩
      | some ch =>
          simp only [hcache, support_bind, Set.mem_iUnion, support_pure,
            Set.mem_singleton_iff, exists_prop] at hrest
          obtain ⟨π, _, rfl⟩ := hrest
          exact ⟨rfl, fun h => by simpa [CmaData.Valid] using h, le_self_add⟩
  · simp only [fs_simp, cmaReal, cmaH3Costly, IsCostlyQuery, IsHashQuery, false_or,
      ite_false, StateT.run_mk] at hz ⊢
    rcases keypair with keypair | ⟨pk, sk⟩
    · simp only [support_bind, Set.mem_iUnion, support_pure, Set.mem_singleton_iff,
        exists_prop] at hz
      obtain ⟨pk_sk, hgen, rfl⟩ := hz
      exact ⟨rfl, fun _ => hr.gen_sound pk_sk.1 pk_sk.2 hgen, by simp⟩
    · simp only [support_pure, Set.mem_singleton_iff] at hz
      subst z
      exact ⟨rfl, fun h => by simpa [CmaData.Valid] using h, by simp⟩

/-- One step of the real CMA game preserves the bad flag exactly. -/
theorem cmaReal_bad_preserved
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
    (p : CmaState M Commit Chal Stmt Wit)
    (z : (cmaSpec M Commit Chal Resp Stmt).Range t × CmaState M Commit Chal Stmt Wit)
    (hz : z ∈ support (((cmaReal M Commit Chal σ hr) t).run p)) :
    z.2.2 = p.2 :=
  (cmaReal_step_normal_form M Commit Chal σ hr t p z hz).1

/-- Once the real CMA bad flag is true, one real step keeps it true. -/
theorem cmaReal_bad_mono
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel) :
    ∀ (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
      (p : CmaState M Commit Chal Stmt Wit), p.2 = true →
        ∀ z ∈ support (((cmaReal M Commit Chal σ hr) t).run p), z.2.2 = true := by
  intro t p hp z hz
  exact (cmaReal_bad_preserved M Commit Chal σ hr t p z hz).trans hp

/-- The real CMA game never reaches bad from the initial state. -/
theorem cmaReal_prEvent_bad_eq_zero
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    {α : Type}
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) α) :
    Pr{let z ← ((simulateQ (cmaReal M Commit Chal σ hr) A).run
      (cmaInit M Commit Chal Stmt Wit))}[z.2.2 = true] = 0 := by
  refine prEvent_eq_zero_of_forall_mem_support _ _ fun z hz hbad => ?_
  have hpres := simulateQ_bad_preserved_of_step
    (impl := cmaReal M Commit Chal σ hr)
    (fun t p z hz => cmaReal_bad_preserved M Commit Chal σ hr t p z hz)
    A (cmaInit M Commit Chal Stmt Wit) hz
  change z.2.2 = false at hpres
  rw [hpres] at hbad
  contradiction

/-- One real CMA step preserves keypair validity. -/
theorem cmaReal_valid_preserved
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
    (p : CmaState M Commit Chal Stmt Wit)
    (hpvalid : CmaData.Valid (rel := rel) p.1)
    (z : (cmaSpec M Commit Chal Resp Stmt).Range t × CmaState M Commit Chal Stmt Wit)
    (hz : z ∈ support (((cmaReal M Commit Chal σ hr) t).run p)) :
    CmaData.Valid (rel := rel) z.2.1 :=
  (cmaReal_step_normal_form M Commit Chal σ hr t p z hz).2.1 hpvalid

/-- The real CMA handler preserves keypair validity while bad is false. -/
theorem cmaReal_preserves_valid
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel) :
    (cmaReal M Commit Chal σ hr).PreservesNoBadInvariant
      (CmaData.Valid (rel := rel)) := by
  intro t p _ hpvalid z hz
  exact cmaReal_valid_preserved M Commit Chal σ hr t p hpvalid z hz

/-- One real CMA step grows the direct random-oracle cache by at most one on
signing or hash queries, and does not grow it on other queries. -/
theorem cmaReal_roCacheCount_step_le
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
    (p : CmaState M Commit Chal Stmt Wit)
    (z : (cmaSpec M Commit Chal Resp Stmt).Range t × CmaState M Commit Chal Stmt Wit)
    (hz : z ∈ support (((cmaReal M Commit Chal σ hr) t).run p)) :
    QueryCache.enncard z.2.1.2.1 ≤ QueryCache.enncard p.1.2.1 +
      if cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
          (Resp := Resp) (Stmt := Stmt) t ∨
        IsHashQuery (M := M) (Commit := Commit) (Chal := Chal)
          (Resp := Resp) (Stmt := Stmt) t then (1 : ℝ≥0∞) else 0 :=
  (cmaReal_step_normal_form M Commit Chal σ hr t p z hz).2.2

/-- Expected H3 loss from direct signing and hash query bounds.

If the adversary makes at most `qS` signing queries and at most `qH` random
oracle queries, the accumulated state-dependent signing slack is bounded by the
standard `qS * ζ + qS * (qS + qH) * β` expression. -/
theorem cmaH3ExpectedLoss_le_queryBounds
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (ζ_zk β : ℝ≥0∞)
    {α : Type}
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) α)
    {qS qH : ℕ}
    (h_qS : OracleComp.IsQueryBoundP A
      (cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt)) qS)
    (h_qH : OracleComp.IsQueryBoundP A
      (IsHashQuery (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt)) qH) :
    cmaH3ExpectedLoss M Commit Chal σ hr ζ_zk β A qS ≤
      (qS : ℝ≥0∞) * ζ_zk + (qS : ℝ≥0∞) * ((qS : ℝ≥0∞) + qH) * β := by
  change expectedQuerySlack (cmaReal M Commit Chal σ hr)
    (cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
      (Resp := Resp) (Stmt := Stmt))
    (fun s : CmaData M Commit Chal Stmt Wit ↦ ζ_zk + QueryCache.enncard s.2.1 * β)
    A qS (cmaDataInit M Commit Chal Stmt Wit, false) ≤ _
  simpa [cmaDataInit, add_assoc] using
    expectedQuerySlack_resource_le
      (impl := cmaReal M Commit Chal σ hr)
      (chargedQuery := cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt))
      (growthQuery := IsHashQuery (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt))
      (R := fun s : CmaData M Commit Chal Stmt Wit => QueryCache.enncard s.2.1)
      (ζ := ζ_zk) (β := β)
      (h_growth := by
        intro t p _ htg z hz
        simpa [htg] using cmaReal_roCacheCount_step_le M Commit Chal σ hr t p z hz)
      (h_free := by
        intro t p _ hnotCostly hnotHash z hz
        simpa [hnotCostly, hnotHash] using
          cmaReal_roCacheCount_step_le M Commit Chal σ hr t p z hz)
      (oa := A) (qS := qS) (qH := qH)
      (h_qS := h_qS) (h_qH := h_qH)
      (s := cmaDataInit M Commit Chal Stmt Wit)

/-- Build the H3 run facts from the query bound and expected-loss bound. -/
theorem cmaH3RunFacts_of_queryBound_expectedLoss
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (ζ_zk β : ℝ≥0∞)
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) Bool)
    (qS : ℕ) (εBound : ℝ≥0∞)
    (h_queryBound : OracleComp.IsQueryBoundP A
      (cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt)) qS)
    (h_expectedLoss :
      cmaH3ExpectedLoss M Commit Chal σ hr ζ_zk β A qS ≤ εBound) :
    CmaH3RunFacts M Commit Chal σ hr ζ_zk β A qS εBound where
  queryBound := h_queryBound
  badZero := cmaReal_prEvent_bad_eq_zero M Commit Chal σ hr A
  expectedLossLe := h_expectedLoss

/-! ## Non-signing step equality -/

/-- The real and simulated CMA handlers agree on every non-signing query. -/
theorem cmaReal_eq_cmaSim_of_not_costly
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
    (ht : ¬ cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
      (Resp := Resp) (Stmt := Stmt) t)
    (p : CmaState M Commit Chal Stmt Wit) :
    ((cmaReal M Commit Chal σ hr) t).run p =
      ((cmaSim M Commit Chal hr simT) t).run p := by
  rcases p with ⟨⟨log, cache, keypair⟩, bad⟩
  rcases t with n | mc | m | ⟨⟩
  · simp [fs_simp, QueryImpl.Stateful.linkWith_apply_run,
      QueryImpl.Stateful.Frame.linkReshape]
  · cases hcache : cache mc <;>
      simp [fs_simp, QueryImpl.Stateful.linkWith_apply_run,
        QueryImpl.Stateful.Frame.linkReshape, hcache]
  · exact (ht True.intro).elim
  · rcases keypair with _ | ⟨pk, sk⟩ <;>
      simp [fs_simp, QueryImpl.Stateful.linkWith_apply_run,
        QueryImpl.Stateful.Frame.linkReshape]

end H3Obligations

/-! ## Signing-step TV ingredients -/

private structure CmaRealSignGhost
    (Stmt Wit Commit PrvState Chal Resp : Type) where
  pk : Stmt
  sk : Wit
  commit : Commit
  privateState : PrvState
  challenge : Chal
  ghostResponse : Resp
  actualResponse : Resp

private structure CmaSignPublic
    (Stmt Wit Commit Chal Resp : Type) where
  pk : Stmt
  sk : Wit
  commit : Commit
  challenge : Chal
  response : Resp

private def cmaSignPublicOfTranscript
    {Stmt Wit Commit Chal Resp : Type}
    (pk : Stmt) (sk : Wit) (t : Commit × Chal × Resp) :
    CmaSignPublic Stmt Wit Commit Chal Resp where
  pk := pk
  sk := sk
  commit := t.1
  challenge := t.2.1
  response := t.2.2

private def CmaRealSignGhost.public
    {Stmt Wit Commit PrvState Chal Resp : Type}
    (x : CmaRealSignGhost Stmt Wit Commit PrvState Chal Resp) :
    CmaSignPublic Stmt Wit Commit Chal Resp where
  pk := x.pk
  sk := x.sk
  commit := x.commit
  challenge := x.challenge
  response := x.ghostResponse

private def cmaSignKeySource
    (hr : GenerableRelation Stmt Wit rel)
    (s : CmaData M Commit Chal Stmt Wit) :
    ProbComp (Stmt × Wit) :=
  match s.2.2 with
  | some keypair => pure keypair
  | none => hr.gen

private def cmaSignKeyedData
    (s : CmaData M Commit Chal Stmt Wit)
    (pk : Stmt) (sk : Wit) :
    CmaData M Commit Chal Stmt Wit :=
  match s.2.2 with
  | some _ => s
  | none => (s.1, s.2.1, some (pk, sk))

private def cmaRealSignGhostDist [SampleableType Chal]
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (m : M)
    (s : CmaData M Commit Chal Stmt Wit) :
    ProbComp (CmaRealSignGhost Stmt Wit Commit PrvState Chal Resp) := do
  let (pk, sk) ← cmaSignKeySource M Commit Chal hr s
  let (c, prv) ← σ.commit pk sk
  let ch ← $ᵗ Chal
  let ghostResp ← σ.respond pk sk prv ch
  match s.2.1 (m, c) with
  | some cachedCh => do
      let actualResp ← σ.respond pk sk prv cachedCh
      pure {
        pk := pk, sk := sk, commit := c, privateState := prv,
        challenge := ch, ghostResponse := ghostResp, actualResponse := actualResp }
  | none =>
      pure {
        pk := pk, sk := sk, commit := c, privateState := prv,
        challenge := ch, ghostResponse := ghostResp, actualResponse := ghostResp }

private def cmaRealSignPublicDist [SampleableType Chal]
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (s : CmaData M Commit Chal Stmt Wit) :
    ProbComp (CmaSignPublic Stmt Wit Commit Chal Resp) := do
  let (pk, sk) ← cmaSignKeySource M Commit Chal hr s
  cmaSignPublicOfTranscript pk sk <$> σ.realTranscript pk sk

private def cmaSimSignPublicDist
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (s : CmaData M Commit Chal Stmt Wit) :
    ProbComp (CmaSignPublic Stmt Wit Commit Chal Resp) := do
  let (pk, sk) ← cmaSignKeySource M Commit Chal hr s
  let (c, ch, π) ← simT pk
  pure (cmaSignPublicOfTranscript pk sk (c, ch, π))

private lemma cmaRealSignPublicDist_some [SampleableType Chal]
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (log : OuterState M) (cache : RoCache M Commit Chal) (key : Stmt × Wit) :
    cmaRealSignPublicDist M Commit Chal σ hr (log, cache, some key) =
      cmaSignPublicOfTranscript key.1 key.2 <$> σ.realTranscript key.1 key.2 := by
  simp [cmaRealSignPublicDist, cmaSignKeySource]

private lemma cmaSimSignPublicDist_some
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (log : OuterState M) (cache : RoCache M Commit Chal) (key : Stmt × Wit) :
    cmaSimSignPublicDist M Commit Chal hr simT (log, cache, some key) =
      cmaSignPublicOfTranscript key.1 key.2 <$> simT key.1 := by
  simp [cmaSimSignPublicDist, cmaSignKeySource, map_eq_bind_pure_comp]

private lemma cmaRealSignPublicDist_none [SampleableType Chal]
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (log : OuterState M) (cache : RoCache M Commit Chal) :
    cmaRealSignPublicDist M Commit Chal σ hr (log, cache, none) =
      (hr.gen >>= fun key =>
        cmaSignPublicOfTranscript key.1 key.2 <$> σ.realTranscript key.1 key.2) := by
  simp [cmaRealSignPublicDist, cmaSignKeySource]

private lemma cmaSimSignPublicDist_none
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (log : OuterState M) (cache : RoCache M Commit Chal) :
    cmaSimSignPublicDist M Commit Chal hr simT (log, cache, none) =
      (hr.gen >>= fun key => cmaSignPublicOfTranscript key.1 key.2 <$> simT key.1) := by
  simp [cmaSimSignPublicDist, cmaSignKeySource, map_eq_bind_pure_comp]

private def cmaRealSignGhostOut [DecidableEq M] [DecidableEq Commit]
    (m : M)
    (s : CmaData M Commit Chal Stmt Wit)
    (x : CmaRealSignGhost Stmt Wit Commit PrvState Chal Resp) :
    (Commit × Resp) × CmaState M Commit Chal Stmt Wit :=
  let s₁ := cmaSignKeyedData M Commit Chal s x.pk x.sk
  match s₁.2.1 (m, x.commit) with
  | some _ =>
      ((x.commit, x.actualResponse), ((s₁.1 ++ [m], s₁.2.1, s₁.2.2), false))
  | none =>
      let cache₂ := s₁.2.1.cacheQuery (m, x.commit) x.challenge
      ((x.commit, x.ghostResponse), ((s₁.1 ++ [m], cache₂, s₁.2.2), false))

private def cmaSimSignPublicOut [DecidableEq M] [DecidableEq Commit]
    (m : M)
    (s : CmaData M Commit Chal Stmt Wit)
    (x : CmaSignPublic Stmt Wit Commit Chal Resp) :
    (Commit × Resp) × CmaState M Commit Chal Stmt Wit :=
  let s₁ := cmaSignKeyedData M Commit Chal s x.pk x.sk
  match s₁.2.1 (m, x.commit) with
  | some _ =>
      ((x.commit, x.response), ((s₁.1 ++ [m], s₁.2.1, s₁.2.2), true))
  | none =>
      let cache₂ := s₁.2.1.cacheQuery (m, x.commit) x.challenge
      ((x.commit, x.response), ((s₁.1 ++ [m], cache₂, s₁.2.2), false))

private def cmaSimSignPublicBad
    (m : M)
    (s : CmaData M Commit Chal Stmt Wit)
    (x : CmaSignPublic Stmt Wit Commit Chal Resp) : Prop :=
  ∃ ch, s.2.1 (m, x.commit) = some ch

private lemma cmaRealSignGhostOut_eq_cmaSimSignPublicOut_of_not_bad
    [DecidableEq M] [DecidableEq Commit]
    (m : M)
    (s : CmaData M Commit Chal Stmt Wit)
    (x : CmaRealSignGhost Stmt Wit Commit PrvState Chal Resp)
    (y : CmaSignPublic Stmt Wit Commit Chal Resp)
    (hpub : x.public = y)
    (hbad : ¬ cmaSimSignPublicBad M Commit Chal m s y) :
    cmaRealSignGhostOut M Commit Chal m s x =
      cmaSimSignPublicOut M Commit Chal m s y := by
  rcases x with ⟨pk, sk, c, prv, ch, ghostResp, actualResp⟩
  rcases y with ⟨pk', sk', c', ch', resp'⟩
  simp only [CmaRealSignGhost.public, CmaSignPublic.mk.injEq] at hpub
  rcases hpub with ⟨rfl, rfl, rfl, rfl, rfl⟩
  have hmiss : s.2.1 (m, c) = none :=
    Option.eq_none_iff_forall_ne_some.2 fun ch0 h => hbad ⟨ch0, h⟩
  have hmiss_keyed :
      (cmaSignKeyedData M Commit Chal s pk sk).2.1 (m, c) = none := by
    rcases s with ⟨log, cache, keypair⟩
    cases keypair <;> simpa [cmaSignKeyedData] using hmiss
  simp [cmaRealSignGhostOut, cmaSimSignPublicOut, hmiss_keyed]

private lemma cmaSignKeySource_sound
    (hr : GenerableRelation Stmt Wit rel)
    (s : CmaData M Commit Chal Stmt Wit)
    (hvalid : CmaData.Valid (rel := rel) s)
    (key : Stmt × Wit)
    (hkey : key ∈ support (cmaSignKeySource M Commit Chal hr s)) :
    rel key.1 key.2 = true := by
  rcases s with ⟨log, cache, keypair⟩
  cases keypair with
  | none =>
      exact hr.gen_sound key.1 key.2 hkey
  | some keypair =>
      obtain rfl : key = keypair := by simpa [cmaSignKeySource] using hkey
      simpa [CmaData.Valid] using hvalid

private lemma cmaRealSignGhost_public_evalDistEq_publicDist [SampleableType Chal]
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (m : M)
    (s : CmaData M Commit Chal Stmt Wit) :
    CmaRealSignGhost.public <$> cmaRealSignGhostDist M Commit Chal σ hr m s =ᵈ
      cmaRealSignPublicDist M Commit Chal σ hr s := by
  rcases s with ⟨log, cache, keypair⟩
  simp only [cmaRealSignGhostDist, cmaRealSignPublicDist, ChallengeVerifyProtocol.realTranscript,
    cmaSignPublicOfTranscript, map_bind, bind_pure_comp, Functor.map_map]
  refine EvalDistEq.bind_right _ fun key => ?_
  refine EvalDistEq.bind_right _ fun cp => ?_
  refine EvalDistEq.bind_right _ fun ch => ?_
  rw [map_eq_bind_pure_comp]
  refine EvalDistEq.bind_right _ fun ghostResp => ?_
  cases cache.toFn (m, cp.1) with
  | none => exact .rfl
  | some cachedCh =>
      simp only [Functor.map_map, Function.comp_apply, CmaRealSignGhost.public]
      exact OracleComp.EvalDistEq.map_const _ _

private lemma cmaSignPublicDist_etvDist_le_hvzk [SampleableType Chal]
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (ζ_zk : ℝ≥0∞) (hHVZK : σ.HVZK simT ζ_zk)
    (s : CmaData M Commit Chal Stmt Wit)
    (hvalid : CmaData.Valid (rel := rel) s) :
    etvDist
      (cmaRealSignPublicDist M Commit Chal σ hr s)
      (cmaSimSignPublicDist M Commit Chal hr simT s) ≤ ζ_zk := by
  -- A fixed keypair's public transcript is a post-processing of its HVZK transcript.
  have hkey : ∀ key : Stmt × Wit, rel key.1 key.2 = true →
      etvDist (cmaSignPublicOfTranscript key.1 key.2 <$> σ.realTranscript key.1 key.2)
        (cmaSignPublicOfTranscript key.1 key.2 <$> simT key.1) ≤ ζ_zk := fun key hrel =>
    (etvDist_map_le _ _ _).trans (hHVZK key.1 key.2 hrel)
  rcases s with ⟨log, cache, keypair⟩
  cases keypair with
  | some key =>
      rw [cmaRealSignPublicDist_some, cmaSimSignPublicDist_some]
      exact hkey key (by simpa [CmaData.Valid] using hvalid)
  | none =>
      rw [cmaRealSignPublicDist_none, cmaSimSignPublicDist_none]
      refine (etvDist_bind_bind_le_wp_of_support _ _ _ (fun _ => ζ_zk) fun key hkeygen =>
        hkey key (hr.gen_sound key.1 key.2 hkeygen)).trans ?_
      exact wp_le_of_forall_le _ fun _ => le_rfl

private lemma simTranscript_cacheHit_prob_le_roCacheCount_mul
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (β : ℝ≥0∞)
    (hCommit : σ.simCommitPredictability simT β)
    (pk : Stmt) (m : M)
    (cache : RoCache M Commit Chal) :
    Pr{let t ← simT pk}[∃ ch, cache (m, t.1) = some ch] ≤ QueryCache.enncard cache * β := by
  classical
  let commitDist : ProbComp Commit := Prod.fst <$> simT pk
  let hit : Commit → Prop := fun c => ∃ ch, cache (m, c) = some ch
  let S : Finset Commit := (finSupport commitDist).filter hit
  have h_card_le : (S.card : ℝ≥0∞) ≤ QueryCache.enncard cache := by
    let e : (S : Set Commit) ↪ cache.toSet :=
      ⟨fun c => ⟨⟨(m, c.1), Classical.choose (Finset.mem_filter.mp c.2).2⟩,
          Classical.choose_spec (Finset.mem_filter.mp c.2).2⟩,
        fun c₁ c₂ h => Subtype.ext (congrArg (fun x : cache.toSet => x.1.1.2) h)⟩
    simpa only [QueryCache.enncard, Set.encard_coe_eq_coe_finsetCard, ENat.toENNReal_coe]
      using ENat.toENNReal_mono e.encard_le
  calc
    Pr{let t ← simT pk}[∃ ch, cache (m, t.1) = some ch]
        = Pr{let c ← commitDist}[∃ c' ∈ S, c = c'] := by
          rw [prEvent_map]
          refine prEvent_congr_of_support _ _ _ fun t ht => ⟨fun h => ⟨t.1, ?_, rfl⟩, ?_⟩
          · refine Finset.mem_filter.mpr ⟨(mem_finSupport_iff_mem_support _ _).mpr ?_, h⟩
            rw [support_map]
            exact ⟨t, ht, rfl⟩
          · rintro ⟨c', hc', rfl⟩
            exact (Finset.mem_filter.mp hc').2
    _ ≤ ∑ c ∈ S, Pr{let c' ← commitDist}[c' = c] :=
          prEvent_exists_finset_le S commitDist fun c c' => c' = c
    _ ≤ ∑ c ∈ S, β := Finset.sum_le_sum fun c _ => by
          simpa only [commitDist, prEvent_map] using hCommit pk c
    _ = (S.card : ℝ≥0∞) * β := by simp [Finset.sum_const, nsmul_eq_mul]
    _ ≤ QueryCache.enncard cache * β := mul_le_mul' h_card_le le_rfl

private lemma cmaSimSignPublicBad_prob_le_roCacheCount_mul
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (β : ℝ≥0∞)
    (hCommit : σ.simCommitPredictability simT β)
    (m : M)
    (s : CmaData M Commit Chal Stmt Wit) :
    Pr{let y ← cmaSimSignPublicDist M Commit Chal hr simT s}[
        cmaSimSignPublicBad M Commit Chal m s y]
      ≤ QueryCache.enncard s.2.1 * β := by
  classical
  rcases s with ⟨log, cache, keypair⟩
  cases keypair with
  | some key =>
      rw [cmaSimSignPublicDist_some, prEvent_map]
      simpa [cmaSimSignPublicBad, cmaSignPublicOfTranscript] using
        simTranscript_cacheHit_prob_le_roCacheCount_mul M Commit Chal σ simT β hCommit
          key.1 m cache
  | none =>
      rw [cmaSimSignPublicDist_none, prEvent_bind]
      refine wp_le_of_forall_le _ fun key => ?_
      rw [prEvent_map]
      simpa [cmaSimSignPublicBad, cmaSignPublicOfTranscript] using
        simTranscript_cacheHit_prob_le_roCacheCount_mul M Commit Chal σ simT β hCommit
          key.1 m cache

section H3Factoring

variable [DecidableEq M] [DecidableEq Commit] [SampleableType Chal]

private lemma cmaRealSignStep_evalDistEq_ghost
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (m : M)
    (s : CmaData M Commit Chal Stmt Wit) :
    ((cmaReal M Commit Chal σ hr) (CmaQuery.sign m)).run (s, false) =ᵈ
      cmaRealSignGhostOut M Commit Chal m s <$> cmaRealSignGhostDist M Commit Chal σ hr m s := by
  rcases s with ⟨log, cache, keypair⟩
  obtain _ | key := keypair <;>
    (conv_lhs =>
      simp only [cmaReal, cmaRealSourceFull, bind_pure_comp, Prod.mk.eta,
        StateT.run_mk, liftM_bind]) <;>
    (conv_rhs => simp [cmaRealSignGhostDist, cmaSignKeySource])
  on_goal 1 => refine EvalDistEq.bind_right _ fun key => ?_
  all_goals
    refine EvalDistEq.bind_right _ fun cp => ?_
    cases hcache : cache (m, cp.1) with
    | none =>
        simp only [hcache, cmaRealSignGhostOut, cmaSignKeyedData, map_pure, bind_pure_comp]
        exact .rfl
    | some cachedCh =>
        conv_lhs => simp [hcache, cmaRealSignGhostOut, cmaSignKeyedData]
        conv_rhs => simp [hcache, cmaRealSignGhostOut, cmaSignKeyedData]
        refine EvalDistEq.symm ?_
        refine (EvalDistEq.bind_right _ fun ch => OracleComp.EvalDistEq.bind_const _ _).trans ?_
        exact OracleComp.EvalDistEq.bind_const _ _

private lemma nma_simulateQ_liftM_unif_run {α : Type}
    (hr : GenerableRelation Stmt Wit rel)
    (oa : ProbComp α)
    (s : NmaState M Commit Chal Stmt Wit) :
    (simulateQ (nma M Commit Chal hr)
      (liftM oa : OracleComp (nmaSpec M Commit Chal Stmt) α)).run s =
      (fun a => (a, s)) <$> oa := by
  simpa using
    QueryImpl.Stateful.simulateQ_liftComp_run_of_query
      (h := nma M Commit Chal hr)
      (fun t s => by
        change
          (fun p : unifSpec.Range t × NmaState M Commit Chal Stmt Wit =>
              (p.1, p.2)) <$>
              ((fun a : unifSpec.Range t => (a, s)) <$>
                (liftM (unifSpec.query t) : ProbComp (unifSpec.Range t))) =
            (fun a : unifSpec.Range t => (a, s)) <$>
              (liftM (unifSpec.query t) : ProbComp (unifSpec.Range t))
        simp [Functor.map_map])
      oa s

private lemma cmaSimSignStep_evalDistEq_public
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (m : M)
    (s : CmaData M Commit Chal Stmt Wit) :
    ((cmaSim M Commit Chal hr simT) (CmaQuery.sign m)).run (s, false) =ᵈ
      cmaSimSignPublicOut M Commit Chal m s <$> cmaSimSignPublicDist M Commit Chal hr simT s := by
  rcases s with ⟨log, cache, keypair⟩
  unfold cmaSim
  obtain _ | key := keypair <;>
    (conv_lhs =>
      simp only [cmaFrame, cmaOuterLens, Prod.mk.eta, cmaNmaLens,
        QueryImpl.Stateful.linkWith_apply_run, cmaToNma, cmaSignSim, liftComp_eq_liftM,
        bind_pure_comp, PFunctor.Lens.State.mk_get, StateT.run_mk, simulateQ_bind,
        simulateQ_query, OracleQuery.input_query, OracleQuery.cont_query, nma, nmaPublic,
        id_map, simulateQ_map, nmaProgram, StateT.run_bind, StateT.run_map, pure_bind,
        bind_map_left, map_bind, Functor.map_map, QueryImpl.Stateful.Frame.linkReshape,
        PFunctor.Lens.State.mk_put, liftM_bind, liftM_map]) <;>
    (conv_rhs => simp [cmaSimSignPublicDist, cmaSignKeySource])
  on_goal 1 => refine EvalDistEq.bind_right _ fun key => ?_
  all_goals
    rw [nma_simulateQ_liftM_unif_run M Commit Chal hr (simT key.1) (cache, some key, false),
      bind_map_left, map_eq_bind_pure_comp]
    refine EvalDistEq.bind_right _ fun t => ?_
    cases hcache : cache.toFn (m, t.1) with
    | none =>
        simp only [hcache, cmaSimSignPublicOut, cmaSignKeyedData, cmaSignPublicOfTranscript,
          map_pure, Function.comp_apply]
        exact .rfl
    | some cachedCh =>
        simp only [hcache, cmaSimSignPublicOut, cmaSignKeyedData, cmaSignPublicOfTranscript,
          map_pure, Function.comp_apply]
        exact .rfl

/-- On a valid keypair state, the total-variation distance between the real and simulated
signing oracle on a single signing query is bounded by `cmaSignEpsCore`. -/
theorem cmaReal_cmaSim_etvDist_sign_le_cmaSignEpsCore_of_valid
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (ζ_zk β : ℝ≥0∞)
    (hHVZK : σ.HVZK simT ζ_zk)
    (hCommit : σ.simCommitPredictability simT β)
    (m : M) (s : CmaData M Commit Chal Stmt Wit)
    (hvalid : CmaData.Valid (rel := rel) s) :
    etvDist
      (((cmaReal M Commit Chal σ hr) (CmaQuery.sign m)).run (s, false))
      (((cmaSim M Commit Chal hr simT) (CmaQuery.sign m)).run (s, false))
      ≤ cmaSignEpsCore M Commit Chal ζ_zk β s := by
  let realGhost := cmaRealSignGhostDist M Commit Chal σ hr m s
  let simPub := cmaSimSignPublicDist M Commit Chal hr simT s
  have hstep : etvDist
        (((cmaReal M Commit Chal σ hr) (CmaQuery.sign m)).run (s, false))
        (((cmaSim M Commit Chal hr simT) (CmaQuery.sign m)).run (s, false)) =
      etvDist (cmaRealSignGhostOut M Commit Chal m s <$> realGhost)
        (cmaSimSignPublicOut M Commit Chal m s <$> simPub) := by
    rw [(cmaRealSignStep_evalDistEq_ghost M Commit Chal σ hr m s).etvDist_congr_left,
      (cmaSimSignStep_evalDistEq_public M Commit Chal hr simT m s).etvDist_congr_right]
  have hprivate := etvDist_map_le_map_add_prEvent_bad realGhost simPub
    CmaRealSignGhost.public (cmaRealSignGhostOut M Commit Chal m s)
    (cmaSimSignPublicOut M Commit Chal m s) (cmaSimSignPublicBad M Commit Chal m s)
    fun x y hpub hbad =>
      cmaRealSignGhostOut_eq_cmaSimSignPublicOut_of_not_bad M Commit Chal m s x y hpub hbad
  have hpublic : etvDist (CmaRealSignGhost.public <$> realGhost) simPub ≤ ζ_zk := by
    rw [(cmaRealSignGhost_public_evalDistEq_publicDist M Commit Chal σ hr m s).etvDist_congr_left]
    exact cmaSignPublicDist_etvDist_le_hvzk M Commit Chal σ hr simT ζ_zk hHVZK s hvalid
  have hbad := cmaSimSignPublicBad_prob_le_roCacheCount_mul M Commit Chal σ hr simT β hCommit m s
  rw [hstep]
  exact (hprivate.trans (add_le_add hpublic hbad)).trans_eq rfl

theorem cmaReal_cmaSim_etvDist_costly_le_cmaSignEpsCore_of_valid
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (ζ_zk β : ℝ≥0∞)
    (hHVZK : σ.HVZK simT ζ_zk)
    (hCommit : σ.simCommitPredictability simT β)
    (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
    (ht : cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
      (Resp := Resp) (Stmt := Stmt) t)
    (s : CmaData M Commit Chal Stmt Wit)
    (hvalid : CmaData.Valid (rel := rel) s) :
    etvDist
      (((cmaReal M Commit Chal σ hr) t).run (s, false))
      (((cmaSim M Commit Chal hr simT) t).run (s, false))
      ≤ cmaSignEpsCore M Commit Chal ζ_zk β s := by
  rcases t with n | mc | m | ⟨⟩
  · exact ht.elim
  · exact ht.elim
  · exact cmaReal_cmaSim_etvDist_sign_le_cmaSignEpsCore_of_valid
      M Commit Chal σ hr simT ζ_zk β hHVZK hCommit m s hvalid
  · exact ht.elim

/-- Build the H3 step facts from HVZK and simulator commit predictability. -/
theorem cmaH3StepFacts_of_hvzk_predictability
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (ζ_zk β : ℝ≥0∞)
    (hHVZK : σ.HVZK simT ζ_zk)
    (hCommit : σ.simCommitPredictability simT β) :
    CmaH3StepFacts M Commit Chal σ hr simT ζ_zk β where
  preservesValid := cmaReal_preserves_valid M Commit Chal σ hr
  stepTvCostly t ht s hvalid :=
    cmaReal_cmaSim_etvDist_costly_le_cmaSignEpsCore_of_valid
      M Commit Chal σ hr simT ζ_zk β hHVZK hCommit t ht s hvalid
  stepEqFree := cmaReal_eq_cmaSim_of_not_costly M Commit Chal σ hr simT
  badMono := cmaReal_bad_mono M Commit Chal σ hr

/-! ## H3 factoring theorem -/

/-- H3 bridge with caller-supplied expected-cost bound.

The hypotheses are factored into per-query step facts and computation-specific run facts; no heap
package or state projection appears in the statement. -/
theorem cmaReal_cmaSim_advantage_le_H3_bound_of_expectedQuerySlack
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (ζ_zk β : ℝ≥0∞)
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) Bool)
    (qS : ℕ) (εBound : ℝ≥0∞)
    (stepFacts : CmaH3StepFacts M Commit Chal σ hr simT ζ_zk β)
    (runFacts : CmaH3RunFacts M Commit Chal σ hr ζ_zk β A qS εBound) :
    cmaH3Advantage M Commit Chal σ hr simT A ≤ εBound := by
  have h_bridge :=
    QueryImpl.Stateful.advantage_le_expectedQuerySlack_add_prEvent_bad_of_inv_preserved
      (h₀ := cmaReal M Commit Chal σ hr)
      (h₁ := cmaSim M Commit Chal hr simT)
      (s_init := cmaDataInit M Commit Chal Stmt Wit)
      (Inv := CmaData.Valid (rel := rel))
      (chargedQuery := cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt))
      (querySlack := cmaSignEpsCore M Commit Chal ζ_zk β)
      (h_init_inv := cmaDataInit_valid M Commit Chal)
      stepFacts.preservesValid stepFacts.stepTvCostly
      (fun t ht s => stepFacts.stepEqFree t ht (s, false))
      stepFacts.badMono A runFacts.queryBound
  calc
    cmaH3Advantage M Commit Chal σ hr simT A
        ≤ expectedQuerySlack (cmaReal M Commit Chal σ hr)
          (cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
            (Resp := Resp) (Stmt := Stmt))
          (cmaSignEpsCore M Commit Chal ζ_zk β) A qS
          (cmaDataInit M Commit Chal Stmt Wit, false)
        + Pr{let z ← ((simulateQ (cmaReal M Commit Chal σ hr) A).run
            (cmaDataInit M Commit Chal Stmt Wit, false))}[z.2.2 = true] := h_bridge
    _ = cmaH3ExpectedLoss M Commit Chal σ hr ζ_zk β A qS := by
            simp [runFacts.badZero, cmaH3ExpectedLoss]
    _ ≤ εBound := runFacts.expectedLossLe

/-- Fully assembled H3 bound from HVZK, simulator commit predictability, and adversary
signing/hash query budgets. -/
theorem cmaReal_cmaSim_advantage_le_H3_bound
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (ζ_zk β : ℝ≥0∞)
    (hHVZK : σ.HVZK simT ζ_zk)
    (hCommit : σ.simCommitPredictability simT β)
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) Bool)
    {qS qH : ℕ}
    (h_qS : OracleComp.IsQueryBoundP A
      (cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt)) qS)
    (h_qH : OracleComp.IsQueryBoundP A
      (IsHashQuery (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt)) qH) :
    cmaH3Advantage M Commit Chal σ hr simT A ≤
      (qS : ℝ≥0∞) * ζ_zk + (qS : ℝ≥0∞) * ((qS : ℝ≥0∞) + qH) * β :=
  cmaReal_cmaSim_advantage_le_H3_bound_of_expectedQuerySlack
    M Commit Chal σ hr simT ζ_zk β A qS
    ((qS : ℝ≥0∞) * ζ_zk + (qS : ℝ≥0∞) * ((qS : ℝ≥0∞) + qH) * β)
    (cmaH3StepFacts_of_hvzk_predictability M Commit Chal σ hr simT
      ζ_zk β hHVZK hCommit)
    (cmaH3RunFacts_of_queryBound_expectedLoss M Commit Chal σ hr ζ_zk β A qS
      ((qS : ℝ≥0∞) * ζ_zk + (qS : ℝ≥0∞) * ((qS : ℝ≥0∞) + qH) * β)
      h_qS
      (cmaH3ExpectedLoss_le_queryBounds M Commit Chal σ hr ζ_zk β A h_qS h_qH))

end H3Factoring

end FiatShamir.Stateful
