/-
Copyright (c) 2026 Devon Tuma. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Devon Tuma
-/
module

public import Mathlib.MeasureTheory.MeasurableSpace.Constructions
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding

/-!
# The measurable coproduct structure on `Except`

`Except ε α` is given the coproduct measurable space generated by its `error` and `ok`
constructors. This is the measurable structure needed to retain exceptions as outcomes when
interpreting `ExceptT` probabilistically.
-/

@[expose] public section

open MeasureTheory

namespace Except

variable {ε α β : Type*}

/-- The coproduct measurable space on `Except ε α`. -/
instance instMeasurableSpace [mε : MeasurableSpace ε] [mα : MeasurableSpace α] :
    MeasurableSpace (Except ε α) :=
  mε.map error ⊓ mα.map ok

@[fun_prop]
theorem measurable_error [MeasurableSpace ε] [MeasurableSpace α] :
    Measurable (@error ε α) :=
  Measurable.of_le_map inf_le_left

@[fun_prop]
theorem measurable_ok [MeasurableSpace ε] [MeasurableSpace α] :
    Measurable (@ok ε α) :=
  Measurable.of_le_map inf_le_right

/-- A set of exception values is measurable exactly when both constructor preimages are
measurable. -/
theorem measurableSet_except_iff [MeasurableSpace ε] [MeasurableSpace α]
    {s : Set (Except ε α)} :
    MeasurableSet s ↔
      MeasurableSet (Except.error ⁻¹' s) ∧ MeasurableSet (Except.ok ⁻¹' s) :=
  Iff.rfl

/-- The image of a measurable set under `Except.error` is measurable. -/
@[simp]
theorem measurableSet_error_image [MeasurableSpace ε] [MeasurableSpace α]
    {s : Set ε} :
    MeasurableSet (Except.error '' s : Set (Except ε α)) ↔ MeasurableSet s := by
  rw [measurableSet_except_iff,
    Set.preimage_image_eq s (fun _ _ h => Except.error.inj h)]
  have hok : Except.ok ⁻¹' (Except.error '' s : Set (Except ε α)) = ∅ := by
    ext value
    simp
  rw [hok]
  simp

/-- The image of a measurable set under `Except.ok` is measurable. -/
@[simp]
theorem measurableSet_ok_image [MeasurableSpace ε] [MeasurableSpace α]
    {s : Set α} :
    MeasurableSet (Except.ok '' s : Set (Except ε α)) ↔ MeasurableSet s := by
  rw [measurableSet_except_iff,
    Set.preimage_image_eq s (fun _ _ h => Except.ok.inj h)]
  have herror : Except.error ⁻¹' (Except.ok '' s : Set (Except ε α)) = ∅ := by
    ext error
    simp
  rw [herror]
  simp

/-- `Except.error` embeds the error branch into the coproduct measurable space. -/
theorem measurableEmbedding_error [MeasurableSpace ε] [MeasurableSpace α] :
    MeasurableEmbedding (@Except.error ε α) where
  injective := fun _ _ h => Except.error.inj h
  measurable := measurable_error
  measurableSet_image' _ hs := measurableSet_error_image.mpr hs

/-- `Except.ok` embeds the successful branch into the coproduct measurable space. -/
theorem measurableEmbedding_ok [MeasurableSpace ε] [MeasurableSpace α] :
    MeasurableEmbedding (@Except.ok ε α) where
  injective := fun _ _ h => Except.ok.inj h
  measurable := measurable_ok
  measurableSet_image' _ hs := measurableSet_ok_image.mpr hs

/-- A function out of `Except ε α` is measurable when both constructor branches are. -/
theorem measurable_elim [MeasurableSpace ε] [MeasurableSpace α] [MeasurableSpace β]
    {f : Except ε α → β} (hError : Measurable (f ∘ error))
    (hOk : Measurable (f ∘ ok)) : Measurable f :=
  Measurable.of_comap_le <| le_inf
    (MeasurableSpace.comap_le_iff_le_map.2 hError)
    (MeasurableSpace.comap_le_iff_le_map.2 hOk)

/-- Mapping the successful value of an exception preserves measurability. -/
@[fun_prop]
theorem measurable_map [MeasurableSpace ε] [MeasurableSpace α] [MeasurableSpace β]
    {f : α → β} (hf : Measurable f) : Measurable (Except.map (ε := ε) f) :=
  measurable_elim measurable_error (measurable_ok.comp hf)

instance instDiscreteMeasurableSpace [MeasurableSpace ε] [MeasurableSpace α]
    [DiscreteMeasurableSpace ε] [DiscreteMeasurableSpace α] :
    DiscreteMeasurableSpace (Except ε α) where
  forall_measurableSet s := by
    change MeasurableSet (error ⁻¹' s) ∧ MeasurableSet (ok ⁻¹' s)
    exact ⟨MeasurableSet.of_discrete, MeasurableSet.of_discrete⟩

end Except
