/-
Copyright (c) 2026 Devon Tuma. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Devon Tuma
-/
module

public import Mathlib.MeasureTheory.MeasurableSpace.Constructions

/-!
# The measurable coproduct structure on `Option`

Mathlib gives `Sum α β` the coproduct measurable space, but does not currently provide the
corresponding instance for `Option α`. This file gives `Option α` the coproduct structure generated
by `some : α → Option α` and the distinguished `none` point. In particular, optional values over a
discrete space are again discrete.
-/

@[expose] public section

open MeasureTheory

namespace Option

variable {α β : Type*}

/-- The coproduct measurable space on `Option α`, generated by `some` and `none`. -/
instance instMeasurableSpace [m : MeasurableSpace α] : MeasurableSpace (Option α) :=
  m.map some ⊓ (⊤ : MeasurableSpace Unit).map fun _ => none

@[fun_prop]
theorem measurable_some [MeasurableSpace α] : Measurable (@some α) :=
  Measurable.of_le_map inf_le_left

theorem measurable_none [MeasurableSpace α] : Measurable (fun _ : Unit => (none : Option α)) :=
  Measurable.of_le_map inf_le_right

/-- The set of present optional values is measurable. -/
theorem measurableSet_isSome [MeasurableSpace α] :
    MeasurableSet {value : Option α | value.isSome} := by
  change MeasurableSet (some ⁻¹' {value : Option α | value.isSome}) ∧
    MeasurableSet ((fun _ : Unit => (none : Option α)) ⁻¹'
      {value : Option α | value.isSome})
  simp

/-- A function out of `Option α` is measurable when its `none` and `some` branches are. -/
theorem measurable_elim [MeasurableSpace α] [MeasurableSpace β] {f : Option α → β}
    (hNone : Measurable (fun _ : Unit => f none))
    (hSome : Measurable (f ∘ some)) : Measurable f :=
  Measurable.of_comap_le <| le_inf
    (MeasurableSpace.comap_le_iff_le_map.2 hSome)
    (MeasurableSpace.comap_le_iff_le_map.2 hNone)

instance instDiscreteMeasurableSpace [MeasurableSpace α] [DiscreteMeasurableSpace α] :
    DiscreteMeasurableSpace (Option α) where
  forall_measurableSet s := by
    change MeasurableSet (some ⁻¹' s) ∧
      MeasurableSet ((fun _ : Unit => (none : Option α)) ⁻¹' s)
    exact ⟨MeasurableSet.of_discrete, MeasurableSet.of_discrete⟩

end Option
