#!/usr/bin/env bash
# scripts/check-extern-isolation.sh
#
# Enforce the layering contract around the `Extern/` library, which holds the
# native `@[extern]` FFI bindings and every module whose transitive imports
# reach them.
#
# The `third_party/` native backends are git submodules, absent by default in
# fresh clones and in Lake dependency checkouts, where the `extern_lib`
# targets fall back to empty stub archives. Executables that link modules
# referencing the native FFI symbols then fail with undefined references, so
# proof-facing libraries must never import from `Extern.…` — that keeps them
# (and anything downstream of them) link-safe without the backends. Test
# libraries (`VCVioTest`, `LatticeCryptoTest`, `HashSigTest`) may import
# `Extern.…`; their native executables run in the nightly FFI workflow.
#
# Exit code:
#   0 — no violations.
#   1 — at least one violation; offending lines are printed to stderr.
#
# Usage:
#   scripts/check-extern-isolation.sh        # check the whole repo
#   scripts/check-extern-isolation.sh --help # this help text
#
# The script uses `rg` if available (fast), otherwise falls back to `grep`.
set -euo pipefail

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'
  exit 0
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# Keep the `rg` and `grep` branches on the same surface area (see
# scripts/check-interop-isolation.sh for the rationale).
if command -v rg >/dev/null 2>&1; then
  SEARCH=(rg --no-heading --line-number --color=never --glob '*.lean')
else
  SEARCH=(grep -RHn -E --include='*.lean')
fi

# Libraries that must not depend on the native FFI surface.
PROOF_LIBS=(VCVio LatticeCrypto ToMathlib HashSig Examples VCVioWidgets Interop)

violations=0

extern_forbidden_re='^[[:space:]]*import[[:space:]]+Extern(\.|[[:space:]]|$)'

for lib in "${PROOF_LIBS[@]}"; do
  if [[ ! -d "$lib" ]]; then
    continue
  fi
  matches="$("${SEARCH[@]}" "$extern_forbidden_re" "$lib" 2>/dev/null || true)"
  if [[ -n "$matches" ]]; then
    echo "ERROR: forbidden import in library '$lib/' (must stay link-safe without native backends, so must not depend on Extern):" >&2
    echo "$matches" >&2
    echo >&2
    violations=$((violations + 1))
  fi
done

# Also check the umbrella `.lean` files at the repo root (e.g.
# `LatticeCrypto.lean`); they are regenerated by `scripts/update-lib.sh` from
# the library directories, so a violation here means a module landed in the
# wrong directory.
for lib in "${PROOF_LIBS[@]}"; do
  umbrella="${lib}.lean"
  if [[ -f "$umbrella" ]]; then
    matches="$("${SEARCH[@]}" "$extern_forbidden_re" "$umbrella" 2>/dev/null || true)"
    if [[ -n "$matches" ]]; then
      echo "ERROR: forbidden import in umbrella '$umbrella' (must not depend on Extern):" >&2
      echo "$matches" >&2
      echo >&2
      violations=$((violations + 1))
    fi
  fi
done

if (( violations > 0 )); then
  echo "Extern isolation check: ${violations} violation(s) found." >&2
  echo "See scripts/check-extern-isolation.sh and the Extern docstring in lakefile.lean for the contract." >&2
  exit 1
fi

echo "Extern isolation check: OK."
