/-
Copyright (c) 2026 IAOM / Equation Capital dba Apoth3osis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Abraxas1010 (IAOM / Apoth3osis)
-/

import VCVio.CryptoFoundations.MerkleTree.Inductive.Defs
import VCVio.CryptoFoundations.TweakableHash

/-!
# Tweaked Merkle Authentication Paths

Merkle trees whose node hash is a *tweakable* hash (`TweakableHash`), with the tweak varying
by level: the internal node rooting a subtree of skeleton `s` hashes its children under the
tweak `tweakAt s.depth`. This is the tree layout used by hash-based signature schemes in the
XMSS family (including the SLH-DSA / SPHINCS+ functions `H` and the lean-Ethereum leanSig
proposal), where domain separation by level is what enables *target*-collision-resistance
assumptions in place of full collision resistance.

Contents:

* `buildMerkleTreeTweaked` / `getPutativeRootTweaked` — tree building and putative-root
  recomputation from a leaf, an authentication path, and a leaf index, hashing each level
  under its own tweak. `generateProof` from the untweaked development is reused unchanged.
* `tweaked_functional_completeness` — honestly generated paths verify.
* `TweakedCollision` and `findCollisionTweaked` — the constructive binding kernel. A
  disagreement between two verifying openings is traced down the two paths and returned as a
  *tweak-tagged* collision: two distinct input pairs with the same digest **under the same
  tweak**. This is exactly the win condition shape of the target-collision experiments in
  `VCVio.CryptoFoundations.HardnessAssumptions.MultiTarget` (SM-TCR), so binding for the
  tweaked tree needs only tweak-wise target collision resistance, not full collision
  resistance of a single function.
* `getPutativeRootTweaked_binding_collision` — the user-facing binding statement: distinct
  leaf values verifying to the same root at the same index yield a `TweakedCollision`,
  as data.

The proofs mirror `VCVio.CryptoFoundations.MerkleTree.Inductive.{Completeness, Binding}`,
generalized from a fixed `hashFn : α → α → α` to a level-indexed family.

## References

- Hülsing, Rijneveld, Song, Schwabe, "Mitigating Multi-Target Attacks in Hash-Based
  Signatures"
- Drake, Khovratovich, Kudinov, Wagner, "Hash-Based Multi-Signatures for Post-Quantum
  Ethereum" (leanSig; CiC 2025)
-/

namespace TweakedMerkleTree

open BinaryTree InductiveMerkleTree

variable {PkSeed Tweak Y : Type}

/-- The node hash at the level of a subtree skeleton `s`: evaluate the tweakable hash under
the tweak assigned to `s.depth`. -/
def levelHash (th : TweakableHash PkSeed Tweak (Y × Y) Y) (pk : PkSeed) (tweakAt : ℕ → Tweak)
    (s : Skeleton) (l r : Y) : Y :=
  th.eval pk (tweakAt s.depth) (l, r)

/-- Build the tweaked Merkle tree: each internal node rooting a subtree of skeleton `s`
hashes its children's roots under the tweak `tweakAt s.depth`. -/
def buildMerkleTreeTweaked (th : TweakableHash PkSeed Tweak (Y × Y) Y) (pk : PkSeed)
    (tweakAt : ℕ → Tweak) : {s : Skeleton} → LeafData Y s → FullData Y s
  | .leaf, .leaf v => .leaf v
  | .internal sl sr, .internal l r =>
    let leftTree := buildMerkleTreeTweaked th pk tweakAt l
    let rightTree := buildMerkleTreeTweaked th pk tweakAt r
    .internal
      (levelHash th pk tweakAt (.internal sl sr) leftTree.getRootValue rightTree.getRootValue)
      leftTree rightTree

/-- Recompute the putative root from a leaf value and an authentication path, hashing each
level under its own tweak. Tweaked analogue of `getPutativeRootWithHash`. -/
def getPutativeRootTweaked (th : TweakableHash PkSeed Tweak (Y × Y) Y) (pk : PkSeed)
    (tweakAt : ℕ → Tweak) : {s : Skeleton} → (idx : SkeletonLeafIndex s) → (leafValue : Y) →
    List.Vector Y idx.depth → Y
  | .leaf, .ofLeaf, leafValue, _ => leafValue
  | .internal sl sr, .ofLeft idxLeft, leafValue, proof =>
    levelHash th pk tweakAt (.internal sl sr)
      (getPutativeRootTweaked th pk tweakAt idxLeft leafValue proof.tail) proof.head
  | .internal sl sr, .ofRight idxRight, leafValue, proof =>
    levelHash th pk tweakAt (.internal sl sr)
      proof.head (getPutativeRootTweaked th pk tweakAt idxRight leafValue proof.tail)

/-- Completeness of tweaked Merkle paths: the honest path (generated by the untweaked
`generateProof`, which only reads cached values) recomputes the root of the honestly built
tweaked tree. -/
theorem tweaked_functional_completeness (th : TweakableHash PkSeed Tweak (Y × Y) Y)
    (pk : PkSeed) (tweakAt : ℕ → Tweak) {s : Skeleton}
    (idx : SkeletonLeafIndex s) (leaves : LeafData Y s) :
    getPutativeRootTweaked th pk tweakAt idx (leaves.get idx)
      (generateProof (buildMerkleTreeTweaked th pk tweakAt leaves) idx)
    = (buildMerkleTreeTweaked th pk tweakAt leaves).getRootValue := by
  induction idx with
  | ofLeaf =>
    cases leaves with
    | leaf a => rfl
  | ofLeft idxLeft ih =>
    cases leaves with
    | internal l r =>
      simp only [buildMerkleTreeTweaked, generateProof, getPutativeRootTweaked,
        FullData.leftSubtree_internal, FullData.rightSubtree_internal,
        List.Vector.head_cons, LeafData.get_internal_ofLeft,
        FullData.internal_getRootValue]
      exact congrArg₂ (fun a b => levelHash th pk tweakAt _ a b) (ih l) rfl
  | ofRight idxRight ih =>
    cases leaves with
    | internal l r =>
      simp only [buildMerkleTreeTweaked, generateProof, getPutativeRootTweaked,
        FullData.leftSubtree_internal, FullData.rightSubtree_internal,
        List.Vector.head_cons, LeafData.get_internal_ofRight,
        FullData.internal_getRootValue]
      exact congrArg₂ (fun a b => levelHash th pk tweakAt _ a b) rfl (ih r)

/-- A tweak-tagged collision: two distinct input pairs with the same digest under the *same*
tweak. This is the win-condition shape of the target-collision experiments in
`HardnessAssumptions.MultiTarget`. -/
def TweakedCollision (th : TweakableHash PkSeed Tweak (Y × Y) Y) (pk : PkSeed)
    (t : Tweak) (p₁ p₂ : Y × Y) : Prop :=
  p₁ ≠ p₂ ∧ th.eval pk t p₁ = th.eval pk t p₂

variable [DecidableEq Y]

/-- Walk two tweaked Merkle branches with the same leaf index, looking for a tweak-tagged
hash collision. Tweaked analogue of `InductiveMerkleTree.findCollision`; the returned tweak
identifies the level (and hence the SM-TCR target) at which the collision occurs. -/
def findCollisionTweaked (th : TweakableHash PkSeed Tweak (Y × Y) Y) (pk : PkSeed)
    (tweakAt : ℕ → Tweak) : {s : Skeleton} → (idx : SkeletonLeafIndex s) →
    (proof₁ proof₂ : List.Vector Y idx.depth) → (x y : Y) → Option (Tweak × (Y × Y) × (Y × Y))
  | .leaf, .ofLeaf, _, _, _, _ => none
  | .internal sl sr, .ofLeft idxLeft, proof₁, proof₂, x, y =>
    let subL1 := getPutativeRootTweaked th pk tweakAt idxLeft x proof₁.tail
    let subL2 := getPutativeRootTweaked th pk tweakAt idxLeft y proof₂.tail
    if (subL1, proof₁.head) = (subL2, proof₂.head) then
      findCollisionTweaked th pk tweakAt idxLeft proof₁.tail proof₂.tail x y
    else if th.eval pk (tweakAt (Skeleton.internal sl sr).depth) (subL1, proof₁.head)
          = th.eval pk (tweakAt (Skeleton.internal sl sr).depth) (subL2, proof₂.head) then
      some (tweakAt (Skeleton.internal sl sr).depth, (subL1, proof₁.head), (subL2, proof₂.head))
    else
      none
  | .internal sl sr, .ofRight idxRight, proof₁, proof₂, x, y =>
    let subR1 := getPutativeRootTweaked th pk tweakAt idxRight x proof₁.tail
    let subR2 := getPutativeRootTweaked th pk tweakAt idxRight y proof₂.tail
    if (proof₁.head, subR1) = (proof₂.head, subR2) then
      findCollisionTweaked th pk tweakAt idxRight proof₁.tail proof₂.tail x y
    else if th.eval pk (tweakAt (Skeleton.internal sl sr).depth) (proof₁.head, subR1)
          = th.eval pk (tweakAt (Skeleton.internal sl sr).depth) (proof₂.head, subR2) then
      some (tweakAt (Skeleton.internal sl sr).depth, (proof₁.head, subR1), (proof₂.head, subR2))
    else
      none

/-- Soundness: a tuple returned by `findCollisionTweaked` is a genuine tweak-tagged
collision. -/
theorem findCollisionTweaked_sound (th : TweakableHash PkSeed Tweak (Y × Y) Y) (pk : PkSeed)
    (tweakAt : ℕ → Tweak) {s : Skeleton} (idx : SkeletonLeafIndex s)
    (proof₁ proof₂ : List.Vector Y idx.depth) (x y : Y) (t : Tweak) (p₁ p₂ : Y × Y)
    (hfind : findCollisionTweaked th pk tweakAt idx proof₁ proof₂ x y = some (t, p₁, p₂)) :
    TweakedCollision th pk t p₁ p₂ := by
  induction idx generalizing x y t p₁ p₂ with
  | ofLeaf =>
    simp [findCollisionTweaked] at hfind
  | ofLeft idxLeft ih =>
    simp only [findCollisionTweaked] at hfind
    split at hfind
    · exact ih proof₁.tail proof₂.tail x y t p₁ p₂ hfind
    · split at hfind
      · rename_i hpair heqhash
        simp only [Option.some.injEq, Prod.mk.injEq] at hfind
        obtain ⟨ht, hp₁, hp₂⟩ := hfind
        subst ht hp₁ hp₂
        exact ⟨hpair, heqhash⟩
      · simp at hfind
  | ofRight idxRight ih =>
    simp only [findCollisionTweaked] at hfind
    split at hfind
    · exact ih proof₁.tail proof₂.tail x y t p₁ p₂ hfind
    · split at hfind
      · rename_i hpair heqhash
        simp only [Option.some.injEq, Prod.mk.injEq] at hfind
        obtain ⟨ht, hp₁, hp₂⟩ := hfind
        subst ht hp₁ hp₂
        exact ⟨hpair, heqhash⟩
      · simp at hfind

/-- Binding for tweaked Merkle paths: two distinct leaf values verifying to the same root at
the same leaf index (under possibly different paths) yield a tweak-tagged collision, found
by `findCollisionTweaked`. -/
theorem getPutativeRootTweaked_binding (th : TweakableHash PkSeed Tweak (Y × Y) Y)
    (pk : PkSeed) (tweakAt : ℕ → Tweak) {s : Skeleton} (idx : SkeletonLeafIndex s)
    (proof₁ proof₂ : List.Vector Y idx.depth) (x y : Y)
    (hne : x ≠ y)
    (heq : getPutativeRootTweaked th pk tweakAt idx x proof₁
         = getPutativeRootTweaked th pk tweakAt idx y proof₂) :
    ∃ t p₁ p₂, findCollisionTweaked th pk tweakAt idx proof₁ proof₂ x y = some (t, p₁, p₂) := by
  induction idx generalizing x y with
  | ofLeaf =>
    simp only [getPutativeRootTweaked] at heq
    exact absurd heq hne
  | ofLeft idxLeft ih =>
    simp only [getPutativeRootTweaked, levelHash] at heq
    by_cases hpair :
        (getPutativeRootTweaked th pk tweakAt idxLeft x proof₁.tail, proof₁.head) =
        (getPutativeRootTweaked th pk tweakAt idxLeft y proof₂.tail, proof₂.head)
    · obtain ⟨t, p₁, p₂, hrec⟩ :=
        ih proof₁.tail proof₂.tail x y hne (congrArg Prod.fst hpair)
      exact ⟨t, p₁, p₂, by simp only [findCollisionTweaked, if_pos hpair]; exact hrec⟩
    · exact ⟨_, _, _, by simp only [findCollisionTweaked, if_neg hpair, if_pos heq]; rfl⟩
  | ofRight idxRight ih =>
    simp only [getPutativeRootTweaked, levelHash] at heq
    by_cases hpair :
        (proof₁.head, getPutativeRootTweaked th pk tweakAt idxRight x proof₁.tail) =
        (proof₂.head, getPutativeRootTweaked th pk tweakAt idxRight y proof₂.tail)
    · obtain ⟨t, p₁, p₂, hrec⟩ :=
        ih proof₁.tail proof₂.tail x y hne (congrArg Prod.snd hpair)
      exact ⟨t, p₁, p₂, by simp only [findCollisionTweaked, if_pos hpair]; exact hrec⟩
    · exact ⟨_, _, _, by simp only [findCollisionTweaked, if_neg hpair, if_pos heq]; rfl⟩

/-- The user-facing Collision Lemma for tweaked Merkle paths: the tuple returned by
`findCollisionTweaked` on two equivocating openings is a genuine tweak-tagged collision —
i.e. a target-collision break at the identified level's tweak. -/
theorem getPutativeRootTweaked_binding_collision (th : TweakableHash PkSeed Tweak (Y × Y) Y)
    (pk : PkSeed) (tweakAt : ℕ → Tweak) {s : Skeleton} (idx : SkeletonLeafIndex s)
    (proof₁ proof₂ : List.Vector Y idx.depth) (x y : Y)
    (hne : x ≠ y)
    (heq : getPutativeRootTweaked th pk tweakAt idx x proof₁
         = getPutativeRootTweaked th pk tweakAt idx y proof₂) :
    ∃ t p₁ p₂,
      findCollisionTweaked th pk tweakAt idx proof₁ proof₂ x y = some (t, p₁, p₂)
        ∧ TweakedCollision th pk t p₁ p₂ := by
  obtain ⟨t, p₁, p₂, hfind⟩ :=
    getPutativeRootTweaked_binding th pk tweakAt idx proof₁ proof₂ x y hne heq
  exact ⟨t, p₁, p₂, hfind,
    findCollisionTweaked_sound th pk tweakAt idx proof₁ proof₂ x y t p₁ p₂ hfind⟩

end TweakedMerkleTree
